// ─────────────────────────────────────────────────────────────────────────────
//  SOUTHERN MAGIC MAP  ––  just its unique data + champ‐spawn override
// ────────────────────────────────────────────────────────────────────────────

using System;
using System.Collections.Generic;
using Server;
using Server.Items;
using Server.Engines.MiniChamps;

namespace Server.Items
{
    public class WesternMagicMap : MagicMapBase
    {
        // –– Unique set of possible coordinates ––
		public override List<Point3D> PredefinedLocations
			=> _overridePredefinedLocations ?? new List<Point3D>
        {
            new Point3D(1881, 2209, 0),
			new Point3D(2087, 2182, 0),
			new Point3D(846, 2008, 0),
			new Point3D(954, 936, 2),
			new Point3D(2162, 2758, 2),
			new Point3D(2335, 3157, 0),
			new Point3D(2677, 3207, 0),
			new Point3D(2833, 2224, 0),
			new Point3D(2930, 1344, 0),
			new Point3D(3667, 397, 0),
			new Point3D(4216, 1455, 0),
			new Point3D(1081, 910, 0),
			new Point3D(637, 2397, 2),
			new Point3D(1565, 2273, 0),
			new Point3D(1690, 2864, 2),
			new Point3D(2162, 2758, 2),
			new Point3D(2942, 3455, 0),
			new Point3D(2449, 768, 2),
			new Point3D(4181, 2973, 0),
			new Point3D(5286, 100, 0),
			new Point3D(5627, 89, 0),
			new Point3D(5925, 130, 0),
			new Point3D(5949, 415, 0),
			new Point3D(5607, 383, 0),
			new Point3D(5306, 286, 0),
			new Point3D(5285, 509, 5),
			new Point3D(5629, 593, 0),
			new Point3D(5892, 625, 0),
			new Point3D(5327, 746, 0),
			new Point3D(5328, 937, 0),
			new Point3D(5590, 855, 0),
			new Point3D(5919, 805, 0),
			new Point3D(5920, 1074, 0),
			new Point3D(5561, 1260, 2),
			new Point3D(5318, 1189, 0),
			new Point3D(5326, 1401, 0),
			new Point3D(5607, 1542, 0),
			new Point3D(5904, 1471, 0),
			new Point3D(5266, 1965, 0),
			new Point3D(5946, 1975, 20),
			new Point3D(5929, 2178, 0),
			new Point3D(5300, 2599, 20),
			new Point3D(5616, 2174, 0)	
        };

        // –– Its own facet ––
		public override Map DestinationFacet
			=> _overrideDestinationFacet ?? Map.Map7;

        // –– Allowed mini-champ types ––
        public List<MiniChampType> AllowedChampTypes => new List<MiniChampType>()
        {
            MiniChampType.CrimsonVeins,
			MiniChampType.AbyssalLair,
			MiniChampType.DiscardedCavernClanRibbon,
			MiniChampType.DiscardedCavernClanScratch,
			MiniChampType.DiscardedCavernClanChitter,
			MiniChampType.EnslavedGoblins,
			MiniChampType.FairyDragonLair,
			MiniChampType.FireTemple,
			MiniChampType.LandsoftheLich,
			MiniChampType.LavaCaldera,
			MiniChampType.PassageofTears,
			MiniChampType.SecretGarden,
			MiniChampType.SkeletalDragon,
			MiniChampType.Encounter1,
			MiniChampType.Encounter2,
			MiniChampType.Encounter3,
			MiniChampType.Encounter4,
			MiniChampType.Encounter5,
			MiniChampType.Encounter6,
			MiniChampType.Encounter7,
			MiniChampType.Encounter8,
			MiniChampType.Encounter9,
			MiniChampType.Encounter10,
			MiniChampType.Encounter11,
			MiniChampType.Encounter12,
			MiniChampType.Encounter13,
			MiniChampType.Encounter14,
			MiniChampType.Encounter15,
			MiniChampType.Encounter16,
			MiniChampType.Encounter17,
			MiniChampType.Encounter18,
			MiniChampType.Encounter19,
			MiniChampType.Encounter20,
			MiniChampType.Encounter21,
			MiniChampType.Encounter22,
			MiniChampType.Encounter23,
			MiniChampType.Encounter24,
			MiniChampType.Encounter25,
			MiniChampType.Encounter26,
			MiniChampType.Encounter27,
			MiniChampType.Encounter28,
			MiniChampType.Encounter29,
			MiniChampType.Encounter30,
			MiniChampType.Encounter31,
			MiniChampType.Encounter32,
			MiniChampType.Encounter33,
			MiniChampType.Encounter34,
			MiniChampType.Encounter35,
			MiniChampType.Encounter36,
			MiniChampType.Encounter37,
			MiniChampType.Encounter38,
			MiniChampType.Encounter39,
			MiniChampType.Encounter40,
			MiniChampType.Encounter41,
			MiniChampType.Encounter42,
			MiniChampType.Encounter43,
			MiniChampType.Encounter44,
			MiniChampType.Encounter45,
			MiniChampType.Encounter46,
			MiniChampType.Encounter47,
			MiniChampType.Encounter48,
			MiniChampType.Encounter49,
			MiniChampType.Encounter50,
			MiniChampType.Encounter51,
			MiniChampType.Encounter52,
			MiniChampType.Encounter53,
			MiniChampType.Encounter54,
			MiniChampType.Encounter55,
			MiniChampType.Encounter56,
			MiniChampType.Encounter57,
			MiniChampType.Encounter58,
			MiniChampType.Encounter59,
			MiniChampType.Encounter60,
			MiniChampType.Encounter61,
			MiniChampType.Encounter62,
			MiniChampType.Encounter63,
			MiniChampType.Encounter64,
			MiniChampType.Encounter65,
			MiniChampType.Encounter66,
			MiniChampType.Encounter67,
			MiniChampType.Encounter68,
			MiniChampType.Encounter69,
			MiniChampType.Encounter70,
			MiniChampType.Encounter71,
			MiniChampType.Encounter72,
			MiniChampType.Encounter73,
			MiniChampType.Encounter74,
			MiniChampType.Encounter75,
			MiniChampType.Encounter76,
			MiniChampType.Encounter77,
			MiniChampType.Encounter78,
			MiniChampType.Encounter79,
			MiniChampType.Encounter80,
			MiniChampType.Encounter81,
			MiniChampType.Encounter82,
			MiniChampType.Encounter83,
			MiniChampType.Encounter84,
			MiniChampType.Encounter85,
			MiniChampType.Encounter86,
			MiniChampType.Encounter87,
			MiniChampType.Encounter88,
			MiniChampType.Encounter89,
			MiniChampType.Encounter90,
			MiniChampType.Encounter91,
			MiniChampType.Encounter92,
			MiniChampType.Encounter93,
			MiniChampType.Encounter94,
			MiniChampType.Encounter95,
			MiniChampType.Encounter96,
			MiniChampType.Encounter97,
			MiniChampType.Encounter98,
			MiniChampType.Encounter99,
			MiniChampType.Encounter100,
			MiniChampType.Encounter101,
			MiniChampType.Encounter102,
			MiniChampType.Encounter103,
			MiniChampType.Encounter104,
			MiniChampType.Encounter105,
			MiniChampType.Encounter106,
			MiniChampType.Encounter107,
			MiniChampType.Encounter108,
			MiniChampType.Encounter109,
			MiniChampType.Encounter110,
			MiniChampType.Encounter111,
			MiniChampType.Encounter112,
			MiniChampType.Encounter113,
			MiniChampType.Encounter114,
			MiniChampType.Encounter115,
			MiniChampType.Encounter116,
			MiniChampType.Encounter117,
			MiniChampType.Encounter118,
			MiniChampType.Encounter119,
			MiniChampType.Encounter120,
			MiniChampType.Encounter121,
			MiniChampType.Encounter122,
			MiniChampType.Encounter123,
			MiniChampType.Encounter124,
			MiniChampType.Encounter125,
			MiniChampType.Encounter126,
			MiniChampType.Encounter127,
			MiniChampType.Encounter128,
			MiniChampType.Encounter129,
			MiniChampType.Encounter130,
			MiniChampType.Encounter131,
			MiniChampType.Encounter132,
			MiniChampType.Encounter133,
			MiniChampType.Encounter134,
			MiniChampType.Encounter135,
			MiniChampType.Encounter136,
			MiniChampType.Encounter137,
			MiniChampType.Encounter138,
			MiniChampType.Encounter139,
			MiniChampType.Encounter140,
			MiniChampType.Encounter141,
			MiniChampType.Encounter142,
			MiniChampType.Encounter143,
			MiniChampType.Encounter144,
			MiniChampType.Encounter145,
			MiniChampType.Encounter146,
			MiniChampType.Encounter147,
			MiniChampType.Encounter148,
			MiniChampType.Encounter149,
			MiniChampType.Encounter150,
			MiniChampType.Encounter151,
			MiniChampType.Encounter152,
			MiniChampType.Encounter153,
			MiniChampType.Encounter154,
			MiniChampType.Encounter155,
			MiniChampType.Encounter156,
			MiniChampType.Encounter157,
			MiniChampType.Encounter158,
			MiniChampType.Encounter159,
			MiniChampType.Encounter160,
			MiniChampType.Encounter161,
			MiniChampType.Encounter162,
			MiniChampType.Encounter163,
			MiniChampType.Encounter164,
			MiniChampType.Encounter165,
			MiniChampType.Encounter166,
			MiniChampType.Encounter167,
			MiniChampType.Encounter168,
			MiniChampType.Encounter169,
			MiniChampType.Encounter170,
			MiniChampType.Encounter171,
			MiniChampType.Encounter172,
			MiniChampType.Encounter173,
			MiniChampType.Encounter174,
			MiniChampType.Encounter175,
			MiniChampType.Encounter176,
			MiniChampType.Encounter177,
			MiniChampType.Encounter178,
			MiniChampType.Encounter179,
			MiniChampType.Encounter180,
			MiniChampType.Encounter181,
			MiniChampType.Encounter182,
			MiniChampType.Encounter183,
			MiniChampType.Encounter184,
			MiniChampType.Encounter185,
			MiniChampType.Encounter186,
			MiniChampType.Encounter187,
			MiniChampType.Encounter188,
			MiniChampType.Encounter189,
			MiniChampType.Encounter190,
			MiniChampType.Encounter191,
			MiniChampType.Encounter192,
			MiniChampType.Encounter193,
			MiniChampType.Encounter194,
			MiniChampType.Encounter195,
			MiniChampType.Encounter196,
			MiniChampType.Encounter197,
			MiniChampType.Encounter198,
			MiniChampType.Encounter199,
			MiniChampType.Encounter200,
			MiniChampType.Encounter201,
			MiniChampType.Encounter202,
			MiniChampType.Encounter203,
			MiniChampType.Encounter204,
			MiniChampType.Encounter205,
			MiniChampType.Encounter206,
			MiniChampType.Encounter207,
			MiniChampType.Encounter208,
			MiniChampType.Encounter209,
			MiniChampType.Encounter210,
			MiniChampType.Encounter211,
			MiniChampType.Encounter212,
			MiniChampType.Encounter213,
			MiniChampType.Encounter214,
			MiniChampType.Encounter215,
			MiniChampType.Encounter216,
			MiniChampType.Encounter217,
			MiniChampType.Encounter218,
			MiniChampType.Encounter219,
			MiniChampType.Encounter220,
			MiniChampType.Encounter221,
			MiniChampType.Encounter222,
			MiniChampType.Encounter223,
			MiniChampType.Encounter224,
			MiniChampType.Encounter225,
			MiniChampType.Encounter226,
			MiniChampType.Encounter227,
			MiniChampType.Encounter228,
			MiniChampType.Encounter229,
			MiniChampType.Encounter230,
			MiniChampType.Encounter231,
			MiniChampType.Encounter232,
			MiniChampType.Encounter233,
			MiniChampType.Encounter234,
			MiniChampType.Encounter235,
			MiniChampType.Encounter236,
			MiniChampType.Encounter237,
			MiniChampType.Encounter238,
			MiniChampType.Encounter239,
			MiniChampType.Encounter240,
			MiniChampType.Encounter241,
			MiniChampType.Encounter242,
			MiniChampType.Encounter243,
			MiniChampType.Encounter244,
			MiniChampType.Encounter245,
			MiniChampType.Encounter246,
			MiniChampType.Encounter247,
			MiniChampType.Encounter248,
			MiniChampType.Encounter249,
			MiniChampType.Encounter250,
			MiniChampType.Encounter251,
			MiniChampType.Encounter252,
			MiniChampType.Encounter253,
			MiniChampType.Encounter254,
			MiniChampType.Encounter255,
			MiniChampType.Encounter256,
			MiniChampType.Encounter257,
			MiniChampType.Encounter258,
			MiniChampType.Encounter259,
			MiniChampType.Encounter260,
			MiniChampType.Encounter261,
			MiniChampType.Encounter262,
			MiniChampType.Encounter263,
			MiniChampType.Encounter264,
			MiniChampType.Encounter265,
			MiniChampType.Encounter266,
			MiniChampType.Encounter267,
			MiniChampType.Encounter268,
			MiniChampType.Encounter269,
			MiniChampType.Encounter270,
			MiniChampType.Encounter271,
			MiniChampType.Encounter272,
			MiniChampType.Encounter273,
			MiniChampType.Encounter274,
			MiniChampType.Encounter275,
			MiniChampType.Encounter276,
			MiniChampType.Encounter277,
			MiniChampType.Encounter278,
			MiniChampType.Encounter279,
			MiniChampType.Encounter280,
			MiniChampType.Encounter281,
			MiniChampType.Encounter282,
			MiniChampType.Encounter283,
			MiniChampType.Encounter284,
			MiniChampType.Encounter285,
			MiniChampType.Encounter286,
			MiniChampType.Encounter287,
			MiniChampType.Encounter288,
			MiniChampType.Encounter289,
			MiniChampType.Encounter290,
			MiniChampType.Encounter291,
			MiniChampType.Encounter292,
			MiniChampType.Encounter293,
			MiniChampType.Encounter294,
			MiniChampType.Encounter295,
			MiniChampType.Encounter296,
			MiniChampType.Encounter297,
			MiniChampType.Encounter298,
			MiniChampType.Encounter299,
			MiniChampType.Encounter300,
			MiniChampType.Encounter301,
			MiniChampType.Encounter302,
			MiniChampType.Encounter303,
			MiniChampType.Encounter304,
			MiniChampType.Encounter305,
			MiniChampType.Encounter306,
			MiniChampType.Encounter307,
			MiniChampType.Encounter308,
			MiniChampType.Encounter309,
			MiniChampType.Encounter310,
			MiniChampType.Encounter311,
			MiniChampType.Encounter312,
			MiniChampType.Encounter313,
			MiniChampType.Encounter314,
			MiniChampType.Encounter315,
			MiniChampType.Encounter316,
			MiniChampType.Encounter317,
			MiniChampType.Encounter318,
			MiniChampType.Encounter319,
			MiniChampType.Encounter320,
			MiniChampType.Encounter321,
			MiniChampType.Encounter322,
			MiniChampType.Encounter323,
			MiniChampType.Encounter324,
			MiniChampType.Encounter325,
			MiniChampType.Encounter326,
			MiniChampType.Encounter327,
			MiniChampType.Encounter328,
			MiniChampType.Encounter329,
			MiniChampType.Encounter330,
			MiniChampType.Encounter331,
			MiniChampType.Encounter332,
			MiniChampType.Encounter333,
			MiniChampType.Encounter334,
			MiniChampType.Encounter335,
			MiniChampType.Encounter336,
			MiniChampType.Encounter337,
			MiniChampType.Encounter338,
			MiniChampType.Encounter339,
			MiniChampType.Encounter340,
			MiniChampType.Encounter341,
			MiniChampType.Encounter342,
			MiniChampType.Encounter343,
			MiniChampType.Encounter344,
			MiniChampType.Encounter345,
			MiniChampType.Encounter346,
			MiniChampType.Encounter347,
			MiniChampType.Encounter348,
			MiniChampType.Encounter349,
			MiniChampType.Encounter350,
			MiniChampType.Encounter351,
			MiniChampType.Encounter352,
			MiniChampType.Encounter353,
			MiniChampType.Encounter354,
			MiniChampType.Encounter355,
			MiniChampType.Encounter356,
			MiniChampType.Encounter357,
			MiniChampType.Encounter358,
			MiniChampType.Encounter359,
			MiniChampType.Encounter360,
			MiniChampType.Encounter361,
			MiniChampType.Encounter362,
			MiniChampType.Encounter363,
			MiniChampType.Encounter364,
			MiniChampType.Encounter365,
			MiniChampType.Encounter366,
			MiniChampType.Encounter367,
			MiniChampType.Encounter368,
			MiniChampType.Encounter369,
			MiniChampType.Encounter370,
			MiniChampType.Encounter371,
			MiniChampType.Encounter372,
			MiniChampType.Encounter373,
			MiniChampType.Encounter374,
			MiniChampType.Encounter375,
			MiniChampType.Encounter376,
			MiniChampType.Encounter377,
			MiniChampType.Encounter378,
			MiniChampType.Encounter379,
			MiniChampType.Encounter380,
			MiniChampType.Encounter381,
			MiniChampType.Encounter382,
			MiniChampType.Encounter383,
			MiniChampType.Encounter384,
			MiniChampType.Encounter385,
			MiniChampType.Encounter386,
			MiniChampType.Encounter387,
			MiniChampType.Encounter388,
			MiniChampType.Encounter389,
			MiniChampType.Encounter390,
			MiniChampType.Encounter391,
			MiniChampType.Encounter392,
			MiniChampType.Encounter393,
			MiniChampType.Encounter394,
			MiniChampType.Encounter395,
			MiniChampType.Encounter396,
			MiniChampType.Encounter397,
			MiniChampType.Encounter398,
			MiniChampType.Encounter399,
			MiniChampType.Encounter400,
			MiniChampType.Encounter401,
			MiniChampType.Encounter402,
			MiniChampType.Encounter403,
			MiniChampType.Encounter404,
			MiniChampType.Encounter405,
			MiniChampType.Encounter406,
			MiniChampType.Encounter407,
			MiniChampType.Encounter408,
			MiniChampType.Encounter409,
			MiniChampType.Encounter410,
			MiniChampType.Encounter411,
			MiniChampType.Encounter412,
			MiniChampType.Encounter413,
			MiniChampType.Encounter414,
			MiniChampType.Encounter415,
			MiniChampType.Encounter416,
			MiniChampType.Encounter417,
			MiniChampType.Encounter418,
			MiniChampType.Encounter419,
			MiniChampType.Encounter420,
			MiniChampType.Encounter421,
			MiniChampType.Encounter422,
			MiniChampType.Encounter423,
			MiniChampType.Encounter424,
			MiniChampType.Encounter425,
			MiniChampType.Encounter426,
			MiniChampType.Encounter427,
			MiniChampType.Encounter428,
			MiniChampType.Encounter429,
			MiniChampType.Encounter430,
			MiniChampType.Encounter431,
			MiniChampType.Encounter432,
			MiniChampType.Encounter433,
			MiniChampType.Encounter434,
			MiniChampType.Encounter435,
			MiniChampType.Encounter436,
			MiniChampType.Encounter437,
			MiniChampType.Encounter438,
			MiniChampType.Encounter439,
			MiniChampType.Encounter440,
			MiniChampType.Encounter441,
			MiniChampType.Encounter442,
			MiniChampType.Encounter443,
			MiniChampType.Encounter444,
			MiniChampType.Encounter445,
			MiniChampType.Encounter446,
			MiniChampType.Encounter447,
			MiniChampType.Encounter448,
			MiniChampType.Encounter449,
			MiniChampType.Encounter450,
			MiniChampType.Encounter451,
			MiniChampType.Encounter452,
			MiniChampType.Encounter453,
			MiniChampType.Encounter454,
			MiniChampType.Encounter455,
			MiniChampType.Encounter456,
			MiniChampType.Encounter457,
			MiniChampType.Encounter458,
			MiniChampType.Encounter459,
			MiniChampType.Encounter460,
			MiniChampType.Encounter461,
			MiniChampType.Encounter462,
			MiniChampType.Encounter463,
			MiniChampType.Encounter464,
			MiniChampType.Encounter465,
			MiniChampType.Encounter466,
			MiniChampType.Encounter467,
			MiniChampType.Encounter468,
			MiniChampType.Encounter469,
			MiniChampType.Encounter470,
			MiniChampType.Encounter471,
			MiniChampType.Encounter472,
			MiniChampType.Encounter473,
			MiniChampType.Encounter474,
			MiniChampType.Encounter475,
			MiniChampType.Encounter476,
			MiniChampType.Encounter477,
			MiniChampType.Encounter478,
			MiniChampType.Encounter479,
			MiniChampType.Encounter480,
			MiniChampType.Encounter481,
			MiniChampType.Encounter482,
			MiniChampType.Encounter483,
			MiniChampType.Encounter484,
			MiniChampType.Encounter485,
			MiniChampType.Encounter486,
			MiniChampType.Encounter487,
			MiniChampType.Encounter488,
			MiniChampType.Encounter489,
			MiniChampType.Encounter490,
			MiniChampType.Encounter491,
			MiniChampType.Encounter492,
			MiniChampType.Encounter493,
			MiniChampType.Encounter494,
			MiniChampType.Encounter495,
			MiniChampType.Encounter496,
			MiniChampType.Encounter497,
			MiniChampType.Encounter498,
			MiniChampType.Encounter499,
			MiniChampType.Encounter500,
			MiniChampType.Encounter501,
			MiniChampType.Encounter502,
			MiniChampType.Encounter503,
			MiniChampType.Encounter504,
			MiniChampType.Encounter505,
			MiniChampType.Encounter506,
			MiniChampType.Encounter507,
			MiniChampType.Encounter508,
			MiniChampType.Encounter509,
			MiniChampType.Encounter510,
			MiniChampType.Encounter511,
			MiniChampType.Encounter512,
			MiniChampType.Encounter513,
			MiniChampType.Encounter514,
			MiniChampType.Encounter515,
			MiniChampType.Encounter516,
			MiniChampType.Encounter517,
			MiniChampType.Encounter518,
			MiniChampType.Encounter519,
			MiniChampType.Encounter520,
			MiniChampType.Encounter521,
			MiniChampType.Encounter522,
			MiniChampType.Encounter523,
			MiniChampType.Encounter524,
			MiniChampType.Encounter525,
			MiniChampType.Encounter526,
			MiniChampType.Encounter527,
			MiniChampType.Encounter528,
			MiniChampType.Encounter529,
			MiniChampType.Encounter530,
			MiniChampType.Encounter531,
			MiniChampType.Encounter532,
			MiniChampType.Encounter533,
			MiniChampType.Encounter534,
			MiniChampType.Encounter535,
			MiniChampType.Encounter536,
			MiniChampType.Encounter537,
			MiniChampType.Encounter538,
			MiniChampType.Encounter539,
			MiniChampType.Encounter540,
			MiniChampType.Encounter541,
			MiniChampType.Encounter542,
			MiniChampType.Encounter543,
			MiniChampType.Encounter544,
			MiniChampType.Encounter545,
			MiniChampType.Encounter546,
			MiniChampType.Encounter547,
			MiniChampType.Encounter548,
			MiniChampType.Encounter549,
			MiniChampType.Encounter550,
			MiniChampType.Encounter551,
			MiniChampType.Encounter552,
			MiniChampType.Encounter553,
			MiniChampType.Encounter554,
			MiniChampType.Encounter555,
			MiniChampType.Encounter556,
			MiniChampType.Encounter557,
			MiniChampType.Encounter558,
			MiniChampType.Encounter559,
			MiniChampType.Encounter560,
			MiniChampType.Encounter561,
			MiniChampType.Encounter562,
			MiniChampType.Encounter563,
			MiniChampType.Encounter564,
			MiniChampType.Encounter565,
			MiniChampType.Encounter566,
			MiniChampType.Encounter567,
			MiniChampType.Encounter568,
			MiniChampType.Encounter569,
			MiniChampType.Encounter570,
			MiniChampType.Encounter571,
			MiniChampType.Encounter572,
			MiniChampType.Encounter573,
			MiniChampType.Encounter574,
			MiniChampType.Encounter575,
			MiniChampType.Encounter576,
			MiniChampType.Encounter577,
			MiniChampType.Encounter578,
			MiniChampType.Encounter579,
			MiniChampType.Encounter580,
			MiniChampType.Encounter581,
			MiniChampType.Encounter582,
			MiniChampType.Encounter583,
			MiniChampType.Encounter584,
			MiniChampType.Encounter585,
			MiniChampType.Encounter586,
			MiniChampType.Encounter587,
			MiniChampType.Encounter588,
			MiniChampType.Encounter589,
			MiniChampType.Encounter590,
			MiniChampType.Encounter591,
			MiniChampType.Encounter592,
			MiniChampType.Encounter593,
			MiniChampType.Encounter594,
			MiniChampType.Encounter595,
			MiniChampType.Encounter596,
			MiniChampType.Encounter597,
			MiniChampType.Encounter598,
			MiniChampType.Encounter599,
			MiniChampType.Encounter600,
			MiniChampType.Encounter601,
			MiniChampType.Encounter602,
			MiniChampType.Encounter603,
			MiniChampType.Encounter604,
			MiniChampType.Encounter605,
			MiniChampType.Encounter606,
			MiniChampType.Encounter607,
			MiniChampType.Encounter608,
			MiniChampType.Encounter609,
			MiniChampType.Encounter610,
			MiniChampType.Encounter611,
			MiniChampType.Encounter612,
			MiniChampType.Encounter613,
			MiniChampType.Encounter614,
			MiniChampType.Encounter615,
			MiniChampType.Encounter616,
			MiniChampType.Encounter617,
			MiniChampType.Encounter618,
			MiniChampType.Encounter619,
			MiniChampType.Encounter620,
			MiniChampType.Encounter621,
			MiniChampType.Encounter622,
			MiniChampType.Encounter623,
			MiniChampType.Encounter624,
			MiniChampType.Encounter625,
			MiniChampType.Encounter626,
			MiniChampType.Encounter627,
			MiniChampType.Encounter628,
			MiniChampType.Encounter629,
			MiniChampType.Encounter630,
			MiniChampType.Encounter631,
			MiniChampType.Encounter632,
			MiniChampType.Encounter633,
			MiniChampType.Encounter634,
			MiniChampType.Encounter635,
			MiniChampType.Encounter636,
			MiniChampType.Encounter637,
			MiniChampType.Encounter638,
			MiniChampType.Encounter639,
			MiniChampType.Encounter640,
			MiniChampType.Encounter641,
			MiniChampType.Encounter642,
			MiniChampType.Encounter643,
			MiniChampType.Encounter644,
			MiniChampType.Encounter645,
			MiniChampType.Encounter646,
			MiniChampType.Encounter647,
			MiniChampType.Encounter648,
			MiniChampType.Encounter649,
			MiniChampType.Encounter650,
			MiniChampType.Encounter651,
			MiniChampType.Encounter652,
			MiniChampType.Encounter653,
			MiniChampType.Encounter654,
			MiniChampType.Encounter655,
			MiniChampType.Encounter656,
			MiniChampType.Encounter657,
			MiniChampType.Encounter658,
			MiniChampType.Encounter659,
			MiniChampType.Encounter660,
			MiniChampType.Encounter661,
			MiniChampType.Encounter662,
			MiniChampType.Encounter663,
			MiniChampType.Encounter664,
			MiniChampType.Encounter665,
			MiniChampType.Encounter666,
			MiniChampType.Encounter667,
			MiniChampType.Encounter668,
			MiniChampType.Encounter669,
			MiniChampType.Encounter670,
			MiniChampType.Encounter671,
			MiniChampType.Encounter672,
			MiniChampType.Encounter673,
			MiniChampType.Encounter674,
			MiniChampType.Encounter675,
			MiniChampType.Encounter676,
			MiniChampType.Encounter677,
			MiniChampType.Encounter678,
			MiniChampType.Encounter679,
			MiniChampType.Encounter680,
			MiniChampType.Encounter681,
			MiniChampType.Encounter682,
			MiniChampType.Encounter683,
			MiniChampType.Encounter684,
			MiniChampType.Encounter685,
			MiniChampType.Encounter686,
			MiniChampType.Encounter687,
			MiniChampType.Encounter688,
			MiniChampType.Encounter689,
			MiniChampType.Encounter690,
			MiniChampType.Encounter691,
			MiniChampType.Encounter692,
			MiniChampType.Encounter693,
			MiniChampType.Encounter694,
			MiniChampType.Encounter695,
			MiniChampType.Encounter696,
			MiniChampType.Encounter697,
			MiniChampType.Encounter698,
			MiniChampType.Encounter699,
			MiniChampType.Encounter700,
			MiniChampType.Encounter701,
			MiniChampType.Encounter702,
			MiniChampType.Encounter703,
			MiniChampType.Encounter704,
			MiniChampType.Encounter705,
			MiniChampType.Encounter706,
			MiniChampType.Encounter707,
			MiniChampType.Encounter708,
			MiniChampType.Encounter709,
			MiniChampType.Encounter710,
			MiniChampType.Encounter711,
			MiniChampType.Encounter712,
			MiniChampType.Encounter713,
			MiniChampType.Encounter714,
			MiniChampType.Encounter715,
			MiniChampType.Encounter716,
			MiniChampType.Encounter717,
			MiniChampType.Encounter718,
			MiniChampType.Encounter719,
			MiniChampType.Encounter720,
			MiniChampType.Encounter721,
			MiniChampType.Encounter722,
			MiniChampType.Encounter723,
			MiniChampType.Encounter724,
			MiniChampType.Encounter725,
			MiniChampType.Encounter726,
			MiniChampType.Encounter727,
			MiniChampType.Encounter728,
			MiniChampType.Encounter729,
			MiniChampType.Encounter730,
			MiniChampType.Encounter731,
			MiniChampType.Encounter732,
			MiniChampType.Encounter733,
			MiniChampType.Encounter734,
			MiniChampType.Encounter735,
			MiniChampType.Encounter736,
			MiniChampType.Encounter737,
			MiniChampType.Encounter738,
			MiniChampType.Encounter739,
			MiniChampType.Encounter740,
			MiniChampType.Encounter741,
			MiniChampType.Encounter742,
			MiniChampType.Encounter743,
			MiniChampType.Encounter744,
			MiniChampType.Encounter745,
			MiniChampType.Encounter746,
			MiniChampType.Encounter747,
			MiniChampType.Encounter748,
			MiniChampType.Encounter749,
			MiniChampType.Encounter750,
			MiniChampType.Encounter751,
			MiniChampType.Encounter752,
			MiniChampType.Encounter753,
			MiniChampType.Encounter754,
			MiniChampType.Encounter755,
			MiniChampType.MeraktusTheTormented,	
        };

        // –– One champ per tier point ––
        public int ChampsToSpawn => Tier;

        [Constructable]
        public WesternMagicMap()
            : base(0x14EB, "Western Lands Magic Map", 677)
        {
        }

        public WesternMagicMap(Serial serial)
            : base(serial)
        {
        }

        /// <summary>
        /// Spawn the mini-champs in a loose circle, plus any extra goodies.
        /// </summary>
        protected override void SpawnChallenges(Point3D centre, Map map, SpawnedContent content, Mobile owner)
        {
            // 1) Mini-champs
            for (int i = 0; i < ChampsToSpawn; i++)
            {
                var type = AllowedChampTypes[Utility.Random(AllowedChampTypes.Count)];
                var pt = new Point3D(
                    centre.X + Utility.RandomMinMax(-10, 10),
                    centre.Y + Utility.RandomMinMax(-10, 10),
                    centre.Z);

                var ctrl = MiniChamp.CreateMiniChampOnFacet(type, SpawnRadius, pt, map);
                content.SpawnedEntities.Add(ctrl);
            }

            // 2) (Optional) sprinkle in cupcakes!
            if (Utility.RandomDouble() < 0.20)
            {
                for (int i = 0; i < 8; i++)
                {
                    var cake = new Cake();  // your custom item
                    var cakePt = new Point3D(
                        centre.X + Utility.RandomMinMax(-2, 2),
                        centre.Y + Utility.RandomMinMax(-2, 2),
                        centre.Z);
                    cake.MoveToWorld(cakePt, map);
                    content.SpawnedEntities.Add(cake);
                }
            }

            // 3) If you also want generic monsters/chests/misc, uncomment:
            // base.SpawnChallenges(centre, map, content, owner);
        }

        // No extra serialization needed: base handles all fields.
		public override void Serialize(GenericWriter writer)
		{
			base.Serialize(writer);
			writer.Write(0); // version 0: no extra fields
		}

		public override void Deserialize(GenericReader reader)
		{
			base.Deserialize(reader);
			int version = reader.ReadInt();
			// (nothing to do here for v0)
		}		
    }
}
