using System;
using System.Collections.Generic;
using Server;
using Server.Items;

namespace Server.Items
{
    public class ItemCollectionType
    {
        public static ItemCollectionType[] Items = new ItemCollectionType[]
        {
            new ItemCollectionType(typeof(Gold), "Gold Coins", 1),
            new ItemCollectionType(typeof(IronOre), "Iron Ore", 2),
            new ItemCollectionType(typeof(Feather), "Feathers", 1),
            new ItemCollectionType(typeof(Bandage), "Bandages", 1),
            new ItemCollectionType(typeof(Apple), "Apples", 1),
            new ItemCollectionType(typeof(BlackPearl), "Black Pearls", 3),
            new ItemCollectionType(typeof(Ginseng), "Ginseng", 2),
            new ItemCollectionType(typeof(SpinedLeather), "Spined Leather", 3),
            new ItemCollectionType(typeof(Bone), "Bones", 1),
            new ItemCollectionType(typeof(Nightshade), "Nightshade", 3),
            new ItemCollectionType(typeof(MandrakeRoot), "Mandrake Root", 2),
            new ItemCollectionType(typeof(SulfurousAsh), "Sulfurous Ash", 2),
            // Add more item types as needed
			new ItemCollectionType(typeof(AgapiteIngot), "Agapite Ingot", 1),
			new ItemCollectionType(typeof(AgilityPotion), "Agility Potion", 1),
			new ItemCollectionType(typeof(AgilityScroll), "Agility Scroll", 1),
			new ItemCollectionType(typeof(Amber), "Amber", 1),
			new ItemCollectionType(typeof(Amethyst), "Amethyst", 1),
			new ItemCollectionType(typeof(AncientWildStaff), "Ancient WildStaff", 1),
			new ItemCollectionType(typeof(AnimateDeadScroll), "AnimateDeadScroll", 1),
			new ItemCollectionType(typeof(Apple), "Apple", 1),
			new ItemCollectionType(typeof(ApplePie), "Apple Pie", 1),
			new ItemCollectionType(typeof(ArcanistsWildStaff), "Arcanists WildStaff", 1),
			new ItemCollectionType(typeof(ArchCureScroll), "ArchCureScroll", 1),
			new ItemCollectionType(typeof(ArchProtectionScroll), "ArchProtectionScroll", 1),
			new ItemCollectionType(typeof(Arrow), "Arrow", 1),
			new ItemCollectionType(typeof(AshLog), "AshLog", 1),
			new ItemCollectionType(typeof(AssassinsShortbow), "Assassins Shortbow", 1),
			new ItemCollectionType(typeof(AwaseMisoSoup), "AwaseMisoSoup", 1),
			new ItemCollectionType(typeof(Axe), "Axe", 1),
			new ItemCollectionType(typeof(Axle), "Axle", 1),
			new ItemCollectionType(typeof(AxleGears), "Axle Gears", 1),
			new ItemCollectionType(typeof(Bacon), "Bacon", 1),
			new ItemCollectionType(typeof(Bandana), "Bandana", 1),
			new ItemCollectionType(typeof(BarbedLongbow), "Barbed Longbow", 1),
			new ItemCollectionType(typeof(Bardiche), "Bardiche", 1),
			new ItemCollectionType(typeof(BarrelHoops), "Barrel Hoops", 1),
			new ItemCollectionType(typeof(BarrelLid), "Barrel Lid", 1),
			new ItemCollectionType(typeof(BarrelStaves), "Barrel Staves", 1),
			new ItemCollectionType(typeof(BarrelTap), "Barrel Tap", 1),
			new ItemCollectionType(typeof(Bascinet), "Bascinet", 1),
			new ItemCollectionType(typeof(BatWing), "Bat Wing", 1),
			new ItemCollectionType(typeof(BattleAxe), "Battle Axe", 1),
			new ItemCollectionType(typeof(Beads), "Beads", 1),
			new ItemCollectionType(typeof(BlackPearl), "Black Pearl", 1),
			new ItemCollectionType(typeof(BladeSpiritsScroll), "BladeSpiritsScroll", 1),
			new ItemCollectionType(typeof(BlessScroll), "BlessScroll", 1),
			new ItemCollectionType(typeof(BloodOathScroll), "BloodOathScroll", 1),
			new ItemCollectionType(typeof(Bloodmoss), "Bloodmoss", 1),
			new ItemCollectionType(typeof(BloodwoodLog), "BloodwoodLog", 1),
			new ItemCollectionType(typeof(Board), "Board", 1),
			new ItemCollectionType(typeof(BodySash), "BodySash", 1),
			new ItemCollectionType(typeof(Bokuto), "Bokuto", 1),
			new ItemCollectionType(typeof(Bolt), "Bolt", 1),
			new ItemCollectionType(typeof(BoltOfCloth), "Bolt Of Cloth", 1),
			new ItemCollectionType(typeof(BoneArms), "Bone Arms", 1),
			new ItemCollectionType(typeof(BoneChest), "Bone Chest", 1),
			new ItemCollectionType(typeof(BoneGloves), "Bone Gloves", 1),
			new ItemCollectionType(typeof(BoneHelm), "Bone Helm", 1),
			new ItemCollectionType(typeof(BoneLegs), "Bone Legs", 1),
			new ItemCollectionType(typeof(Bonnet), "Bonnet", 1),
			new ItemCollectionType(typeof(Boots), "Boots", 1),
			new ItemCollectionType(typeof(Bottle), "Bottle", 1),
			new ItemCollectionType(typeof(Bow), "Bow", 1),
			new ItemCollectionType(typeof(BreadLoaf), "Bread Loaf", 1),
			new ItemCollectionType(typeof(Broadsword), "Broadsword", 1),
			new ItemCollectionType(typeof(BronzeIngot), "Bronze Ingot", 1),
			new ItemCollectionType(typeof(BronzeShield), "Bronze Shield", 1),
			new ItemCollectionType(typeof(Buckler), "Buckler", 1),
			new ItemCollectionType(typeof(ButcherKnife), "Butcher Knife", 1),
			new ItemCollectionType(typeof(Cabbage), "Cabbage", 1),
			new ItemCollectionType(typeof(Cake), "Cake", 1),
			new ItemCollectionType(typeof(Cake), "Cake", 1),
			new ItemCollectionType(typeof(CakeMix), "Cake Mix", 1),
			new ItemCollectionType(typeof(Candelabra), "Candelabra", 1),
			new ItemCollectionType(typeof(Cantaloupe), "Cantaloupe", 1),
			new ItemCollectionType(typeof(Cap), "Cap", 1),
			new ItemCollectionType(typeof(Carrot), "Carrot", 1),
			new ItemCollectionType(typeof(ChainChest), "Chain Chest", 1),
			new ItemCollectionType(typeof(ChainCoif), "Chain Coif", 1),
			new ItemCollectionType(typeof(ChainLegs), "Chain Legs", 1),
			new ItemCollectionType(typeof(ChainLightningScroll), "ChainLightningScroll", 1),
			new ItemCollectionType(typeof(CheesePizza), "Cheese Pizza", 1),
			new ItemCollectionType(typeof(CheeseWheel), "Cheese Wheel", 1),
			new ItemCollectionType(typeof(CherryArmoire), "Cherry Armoire", 1),
			new ItemCollectionType(typeof(ChickenLeg), "Chicken Leg", 1),
			new ItemCollectionType(typeof(ChickenLeg), "Chicken Leg", 1),
			new ItemCollectionType(typeof(Citrine), "Citrine", 1),
			new ItemCollectionType(typeof(Cleaver), "Cleaver", 1),
			new ItemCollectionType(typeof(Clippers), "Clippers", 1),
			new ItemCollectionType(typeof(Cloak), "Cloak", 1),
			new ItemCollectionType(typeof(Clock), "Clock", 1),
			new ItemCollectionType(typeof(ClockFrame), "Clock Frame", 1),
			new ItemCollectionType(typeof(ClockParts), "Clock Parts", 1),
			new ItemCollectionType(typeof(CloseHelm), "Close Helm", 1),
			new ItemCollectionType(typeof(Cloth), "Cloth", 1),
			new ItemCollectionType(typeof(ClumsyScroll), "Clumsy Scroll", 1),
			new ItemCollectionType(typeof(CompositeBow), "Composite Bow", 1),
			new ItemCollectionType(typeof(ConflagrationPotion), "Conflagration Potion", 1),
			new ItemCollectionType(typeof(ConfusionBlastPotion), "ConfusionBlast Potion", 1),
			new ItemCollectionType(typeof(CookedBird), "Cooked Bird", 1),
			new ItemCollectionType(typeof(CookieMix), "Cookie Mix", 1),
			new ItemCollectionType(typeof(Cookies), "Cookies", 1),
			new ItemCollectionType(typeof(CopperIngot), "Copper Ingot", 1),
			new ItemCollectionType(typeof(CorpseSkinScroll), "CorpseSkinScroll", 1),
			new ItemCollectionType(typeof(Cotton), "Cotton", 1),
			new ItemCollectionType(typeof(CreateFoodScroll), "CreateFoodScroll", 1),
			new ItemCollectionType(typeof(Crossbow), "Crossbow", 1),
			new ItemCollectionType(typeof(CunningScroll), "CunningScroll", 1),
			new ItemCollectionType(typeof(CurePotion), "CurePotion", 1),
			new ItemCollectionType(typeof(CureScroll), "CureScroll", 1),
			new ItemCollectionType(typeof(CurseScroll), "CurseScroll", 1),
			new ItemCollectionType(typeof(CurseWeaponScroll), "CurseWeaponScroll", 1),
			new ItemCollectionType(typeof(Cutlass), "Cutlass", 1),
			new ItemCollectionType(typeof(DaemonBlood), "Daemon Blood", 1),
			new ItemCollectionType(typeof(Dagger), "Dagger", 1),
			new ItemCollectionType(typeof(DarkglowPotion), "Darkglow Potion", 1),
			new ItemCollectionType(typeof(DeadlyPoisonPotion), "DeadlyPoison Potion", 1),
			new ItemCollectionType(typeof(Diamond), "Diamond", 1),
			new ItemCollectionType(typeof(DispelFieldScroll), "DispelFieldScroll", 1),
			new ItemCollectionType(typeof(DispelScroll), "DispelScroll", 1),
			new ItemCollectionType(typeof(DoubleAxe), "DoubleAxe", 1),
			new ItemCollectionType(typeof(Doublet), "Doublet", 1),
			new ItemCollectionType(typeof(Dough), "Dough", 1),
			new ItemCollectionType(typeof(Drums), "Drums", 1),
			new ItemCollectionType(typeof(DullCopperIngot), "DullCopper Ingot", 1),
			new ItemCollectionType(typeof(EarOfCorn), "EarOfCorn", 1),
			new ItemCollectionType(typeof(EarthquakeScroll), "EarthquakeScroll", 1),
			new ItemCollectionType(typeof(EggBomb), "EggBomb", 1),
			new ItemCollectionType(typeof(Eggs), "Eggs", 1),
			new ItemCollectionType(typeof(ElegantArmoire), "Elegant Armoire", 1),
			new ItemCollectionType(typeof(ElvenCompositeLongbow), "ElvenComposite Longbow", 1),
			new ItemCollectionType(typeof(Emerald), "Emerald", 1),
			new ItemCollectionType(typeof(EmptyBookcase), "Empty Bookcase", 1),
			new ItemCollectionType(typeof(EnchantedApple), "Enchanted Apple", 1),
			new ItemCollectionType(typeof(EnergyBoltScroll), "EnergyBoltScroll", 1),
			new ItemCollectionType(typeof(EnergyFieldScroll), "EnergyFieldScroll", 1),
			new ItemCollectionType(typeof(EnergyVortexScroll), "EnergyVortexScroll", 1),
			new ItemCollectionType(typeof(EvilOmenScroll), "EvilOmenScroll", 1),
			new ItemCollectionType(typeof(ExecutionersAxe), "Executioners Axe", 1),
			new ItemCollectionType(typeof(ExplosionPotion), "Explosion Potion", 1),
			new ItemCollectionType(typeof(ExplosionScroll), "ExplosionScroll", 1),
			new ItemCollectionType(typeof(FancyDress), "Fancy Dress", 1),
			new ItemCollectionType(typeof(FancyShirt), "Fancy Shirt", 1),
			new ItemCollectionType(typeof(FeatheredHat), "Feathered Hat", 1),
			new ItemCollectionType(typeof(FeeblemindScroll), "FeeblemindScroll", 1),
			new ItemCollectionType(typeof(FemaleLeatherChest), "FemaleLeather Chest", 1),
			new ItemCollectionType(typeof(FemalePlateChest), "FemalePlate Chest", 1),
			new ItemCollectionType(typeof(FemaleStuddedChest), "FemaleS tudded Chest", 1),
			new ItemCollectionType(typeof(FinishedWoodenChest), "Finished Wooden Chest", 1),
			new ItemCollectionType(typeof(FireFieldScroll), "FireFieldScroll", 1),
			new ItemCollectionType(typeof(FireballScroll), "FireballScroll", 1),
			new ItemCollectionType(typeof(Fish), "Fish", 1),
			new ItemCollectionType(typeof(FishSteak), "FishSteak", 1),
			new ItemCollectionType(typeof(Flax), "Flax", 1),
			new ItemCollectionType(typeof(FletcherTools), "Fletcher Tools", 1),
			new ItemCollectionType(typeof(FloppyHat), "Floppy Hat", 1),
			new ItemCollectionType(typeof(FlourSifter), "Flour Sifter", 1),
			new ItemCollectionType(typeof(FootStool), "Foot Stool", 1),
			new ItemCollectionType(typeof(Fork), "Fork", 1),
			new ItemCollectionType(typeof(ForkLeft), "Fork Left", 1),
			new ItemCollectionType(typeof(FriedEggs), "Fried Eggs", 1),
			new ItemCollectionType(typeof(Froe), "Froe", 1),
			new ItemCollectionType(typeof(FrozenLongbow), "Frozen Longbow", 1),
			new ItemCollectionType(typeof(FruitPie), "Fruit Pie", 1),
			new ItemCollectionType(typeof(FullApron), "Full Apron", 1),
			new ItemCollectionType(typeof(Garlic), "Garlic", 1),
			new ItemCollectionType(typeof(GateTravelScroll), "GateTravelScroll", 1),
			new ItemCollectionType(typeof(Gears), "Gears", 1),
			new ItemCollectionType(typeof(GildedWoodenChest), "GildedWoodenChest", 1),
			new ItemCollectionType(typeof(Ginseng), "Ginseng", 1),
			new ItemCollectionType(typeof(Globe), "Globe", 1),
			new ItemCollectionType(typeof(GnarledStaff), "GnarledStaff", 1),
			new ItemCollectionType(typeof(Goblet), "Goblet", 1),
			new ItemCollectionType(typeof(GoldBeadNecklace), "GoldBeadNecklace", 1),
			new ItemCollectionType(typeof(GoldBracelet), "Gold Bracelet", 1),
			new ItemCollectionType(typeof(GoldEarrings), "Gold Earrings", 1),
			new ItemCollectionType(typeof(GoldIngot), "Gold Ingot", 1),
			new ItemCollectionType(typeof(GoldNecklace), "Gold Necklace", 1),
			new ItemCollectionType(typeof(GoldRing), "Gold Ring", 1),
			new ItemCollectionType(typeof(Grapes), "Grapes", 1),
			new ItemCollectionType(typeof(GrapesOfWrath), "Grapes Of Wrath", 1),
			new ItemCollectionType(typeof(GraveDust), "Grave Dust", 1),
			new ItemCollectionType(typeof(GreaterAgilityPotion), "GreaterAgility Potion", 1),
			new ItemCollectionType(typeof(GreaterConflagrationPotion), "GreaterConflagration Potion", 1),
			new ItemCollectionType(typeof(GreaterConfusionBlastPotion), "GreaterConfusionBlast Potion", 1),
			new ItemCollectionType(typeof(GreaterCurePotion), "GreaterCure Potion", 1),
			new ItemCollectionType(typeof(GreaterExplosionPotion), "GreaterExplosion Potion", 1),
			new ItemCollectionType(typeof(GreaterHealPotion), "GreaterHeal Potion", 1),
			new ItemCollectionType(typeof(GreaterHealScroll), "GreaterHeal Scroll", 1),
			new ItemCollectionType(typeof(GreaterPoisonPotion), "GreaterPoison Potion", 1),
			new ItemCollectionType(typeof(GreaterStrengthPotion), "GreaterStrength Potion", 1),
			new ItemCollectionType(typeof(GreenGourd), "Green Gourd", 1),
			new ItemCollectionType(typeof(GreenTea), "Green Tea", 1),
			new ItemCollectionType(typeof(Halberd), "Halberd", 1),
			new ItemCollectionType(typeof(HalfApron), "Half Apron", 1),
			new ItemCollectionType(typeof(Ham), "Ham", 1),
			new ItemCollectionType(typeof(HammerPick), "Hammer Pick", 1),
			new ItemCollectionType(typeof(HardenedWildStaff), "HardenedWild Staff", 1),
			new ItemCollectionType(typeof(HarmScroll), "HarmScroll", 1),
			new ItemCollectionType(typeof(Harp), "Harp", 1),
			new ItemCollectionType(typeof(Hatchet), "Hatchet", 1),
			new ItemCollectionType(typeof(HealPotion), "Heal Potion", 1),
			new ItemCollectionType(typeof(HealScroll), "HealScroll", 1),
			new ItemCollectionType(typeof(HeaterShield), "Heater Shield", 1),
			new ItemCollectionType(typeof(HeavyCrossbow), "Heavy Crossbow", 1),
			new ItemCollectionType(typeof(Helmet), "Helmet", 1),
			new ItemCollectionType(typeof(Hides), "Hides", 1),
			new ItemCollectionType(typeof(Hinge), "Hinge", 1),
			new ItemCollectionType(typeof(HoneydewMelon), "Honeydew Melon", 1),
			new ItemCollectionType(typeof(HorrificBeastScroll), "HorrificBeastScroll", 1),
			new ItemCollectionType(typeof(IncognitoScroll), "IncognitoScroll", 1),
			new ItemCollectionType(typeof(InvisibilityScroll), "InvisibilityScroll", 1),
			new ItemCollectionType(typeof(IronIngot), "Iron Ingot", 1),
			new ItemCollectionType(typeof(JarHoney), "Jar Honey", 1),
			new ItemCollectionType(typeof(JesterHat), "Jester Hat", 1),
			new ItemCollectionType(typeof(JesterSuit), "Jester Suit", 1),
			new ItemCollectionType(typeof(Katana), "Katana", 1),
			new ItemCollectionType(typeof(Key), "Key", 1),
			new ItemCollectionType(typeof(KeyRing), "Key Ring", 1),
			new ItemCollectionType(typeof(Kilt), "Kilt", 1),
			new ItemCollectionType(typeof(Kindling), "Kindling", 1),
			new ItemCollectionType(typeof(Knife), "Knife", 1),
			new ItemCollectionType(typeof(KnifeLeft), "Knife Left", 1),
			new ItemCollectionType(typeof(Kryss), "Kryss", 1),
			new ItemCollectionType(typeof(LambLeg), "LambLeg", 1),
			new ItemCollectionType(typeof(LambLeg), "LambLeg", 1),
			new ItemCollectionType(typeof(Lantern), "Lantern", 1),
			new ItemCollectionType(typeof(LapHarp), "LapHarp", 1),
			new ItemCollectionType(typeof(LargeBattleAxe), "Large Battle Axe", 1),
			new ItemCollectionType(typeof(LargeCrate), "Large Crate", 1),
			new ItemCollectionType(typeof(LeatherArms), "Leather Arms", 1),
			new ItemCollectionType(typeof(LeatherBustierArms), "Leather Bustier Arms", 1),
			new ItemCollectionType(typeof(LeatherCap), "Leather Cap", 1),
			new ItemCollectionType(typeof(LeatherChest), "Leather Chest", 1),
			new ItemCollectionType(typeof(LeatherGloves), "Leather Gloves", 1),
			new ItemCollectionType(typeof(LeatherGorget), "Leather Gorget", 1),
			new ItemCollectionType(typeof(LeatherLegs), "Leather Legs", 1),
			new ItemCollectionType(typeof(LeatherShorts), "Leather Shorts", 1),
			new ItemCollectionType(typeof(LeatherSkirt), "Leather Skirt", 1),
			new ItemCollectionType(typeof(Lemon), "Lemon", 1),
			new ItemCollectionType(typeof(LesserCurePotion), "LesserCure Potion", 1),
			new ItemCollectionType(typeof(LesserCurePotion), "LesserCure Potion", 1),
			new ItemCollectionType(typeof(LesserExplosionPotion), "LesserExplosion Potion", 1),
			new ItemCollectionType(typeof(LesserExplosionPotion), "LesserExplosion Potion", 1),
			new ItemCollectionType(typeof(LesserHealPotion), "LesserHeal Potion", 1),
			new ItemCollectionType(typeof(LesserHealPotion), "LesserHeal Potion", 1),
			new ItemCollectionType(typeof(LesserPoisonPotion), "LesserPoison Potion", 1),
			new ItemCollectionType(typeof(LesserPoisonPotion), "LesserPoison Potion", 1),
			new ItemCollectionType(typeof(Lettuce), "Lettuce", 1),
			new ItemCollectionType(typeof(LichFormScroll), "LichFormScroll", 1),
			new ItemCollectionType(typeof(LightningScroll), "LightningScroll", 1),
			new ItemCollectionType(typeof(LightweightShortbow), "Lightweight Shortbow", 1),
			new ItemCollectionType(typeof(Lime), "Lime", 1),
			new ItemCollectionType(typeof(LongPants), "LongPants", 1),
			new ItemCollectionType(typeof(LongbowOfMight), "Longbow Of Might", 1),
			new ItemCollectionType(typeof(Longsword), "Longsword", 1),
			new ItemCollectionType(typeof(Lute), "Lute", 1),
			new ItemCollectionType(typeof(Mace), "Mace", 1),
			new ItemCollectionType(typeof(MagicArrowScroll), "MagicArrowScroll", 1),
			new ItemCollectionType(typeof(MagicLockScroll), "MagicLockScroll", 1),
			new ItemCollectionType(typeof(MagicReflectScroll), "MagicReflectScroll", 1),
			new ItemCollectionType(typeof(MagicTrapScroll), "MagicTrapScroll", 1),
			new ItemCollectionType(typeof(MagicalShortbow), "MagicalShortbow", 1),
			new ItemCollectionType(typeof(ManaDrainScroll), "ManaDrainScroll", 1),
			new ItemCollectionType(typeof(ManaVampireScroll), "ManaVampireScroll", 1),
			new ItemCollectionType(typeof(MandrakeRoot), "MandrakeRoot", 1),
			new ItemCollectionType(typeof(MapleArmoire), "MapleArmoire", 1),
			new ItemCollectionType(typeof(MarkScroll), "MarkScroll", 1),
			new ItemCollectionType(typeof(MassCurseScroll), "MassCurseScroll", 1),
			new ItemCollectionType(typeof(MassDispelScroll), "MassDispelScroll", 1),
			new ItemCollectionType(typeof(Maul), "Maul", 1),
			new ItemCollectionType(typeof(MeatPie), "MeatPie", 1),
			new ItemCollectionType(typeof(MediumCrate), "MediumCrate", 1),
			new ItemCollectionType(typeof(MetalContainerEngraver), "Metal Container Engraver", 1),
			new ItemCollectionType(typeof(MetalKiteShield), "Metal KiteShield", 1),
			new ItemCollectionType(typeof(MetalShield), "Metal Shield", 1),
			new ItemCollectionType(typeof(MeteorSwarmScroll), "MeteorSwarmScroll", 1),
			new ItemCollectionType(typeof(MindBlastScroll), "MindBlastScroll", 1),
			new ItemCollectionType(typeof(MindRotScroll), "MindRotScroll", 1),
			new ItemCollectionType(typeof(MisoSoup), "Miso Soup", 1),
			new ItemCollectionType(typeof(MortarPestle), "Mortar Pestle", 1),
			new ItemCollectionType(typeof(Muffins), "Muffins", 1),
			new ItemCollectionType(typeof(Muffins), "Muffins", 1),
			new ItemCollectionType(typeof(MysticalShortbow), "Mystical Shortbow", 1),
			new ItemCollectionType(typeof(Necklace), "Necklace", 1),
			new ItemCollectionType(typeof(NecromancerSpellbook), "Necromancer Spellbook", 1),
			new ItemCollectionType(typeof(NexusCore), "NexusCore", 1),
			new ItemCollectionType(typeof(NightSightPotion), "NightSight Potion", 1),
			new ItemCollectionType(typeof(NightSightScroll), "NightSightScroll", 1),
			new ItemCollectionType(typeof(Nightshade), "Nightshade", 1),
			new ItemCollectionType(typeof(NorseHelm), "NorseHelm", 1),
			new ItemCollectionType(typeof(NoxCrystal), "NoxCrystal", 1),
			new ItemCollectionType(typeof(Nunchaku), "Nunchaku", 1),
			new ItemCollectionType(typeof(OakLog), "OakLog", 1),
			new ItemCollectionType(typeof(Onion), "Onion", 1),
			new ItemCollectionType(typeof(OrnateWoodenChest), "Ornate Wooden Chest", 1),
			new ItemCollectionType(typeof(PainSpikeScroll), "PainSpikeScroll", 1),
			new ItemCollectionType(typeof(ParalyzeFieldScroll), "ParalyzeFieldScroll", 1),
			new ItemCollectionType(typeof(ParalyzeScroll), "ParalyzeScroll", 1),
			new ItemCollectionType(typeof(ParasiticPotion), "Parasitic Potion", 1),
			new ItemCollectionType(typeof(Peach), "Peach", 1),
			new ItemCollectionType(typeof(PeachCobbler), "Peach Cobbler", 1),
			new ItemCollectionType(typeof(Pear), "Pear", 1),
			new ItemCollectionType(typeof(PewterMug), "PewterMug", 1),
			new ItemCollectionType(typeof(Pickaxe), "Pickaxe", 1),
			new ItemCollectionType(typeof(PigIron), "PigIron", 1),
			new ItemCollectionType(typeof(Pitchfork), "Pitchfork", 1),
			new ItemCollectionType(typeof(PlainDress), "PlainDress", 1),
			new ItemCollectionType(typeof(PlainWoodenChest), "Plain Wooden Chest", 1),
			new ItemCollectionType(typeof(Plate), "Plate", 1),
			new ItemCollectionType(typeof(PlateArms), "Plate Arms", 1),
			new ItemCollectionType(typeof(PlateChest), "Plate Chest", 1),
			new ItemCollectionType(typeof(PlateGloves), "Plate Gloves", 1),
			new ItemCollectionType(typeof(PlateGorget), "Plate Gorget", 1),
			new ItemCollectionType(typeof(PlateHelm), "Plate Helm", 1),
			new ItemCollectionType(typeof(PlateLegs), "Plate Legs", 1),
			new ItemCollectionType(typeof(PoisonFieldScroll), "PoisonFieldScroll", 1),
			new ItemCollectionType(typeof(PoisonPotion), "PoisonPotion", 1),
			new ItemCollectionType(typeof(PoisonScroll), "PoisonScroll", 1),
			new ItemCollectionType(typeof(PoisonStrikeScroll), "PoisonStrikeScroll", 1),
			new ItemCollectionType(typeof(PolymorphScroll), "PolymorphScroll", 1),
			new ItemCollectionType(typeof(PotionKeg), "PotionKeg", 1),
			new ItemCollectionType(typeof(ProtectionScroll), "ProtectionScroll", 1),
			new ItemCollectionType(typeof(Pumpkin), "Pumpkin", 1),
			new ItemCollectionType(typeof(PumpkinPie), "Pumpkin Pie", 1),
			new ItemCollectionType(typeof(QuarterStaff), "Quarter Staff", 1),
			new ItemCollectionType(typeof(Quiche), "Quiche", 1),
			new ItemCollectionType(typeof(RangersShortbow), "Rangers Shortbow", 1),
			new ItemCollectionType(typeof(RawBird), "Raw Bird", 1),
			new ItemCollectionType(typeof(RawChickenLeg), "Raw Chicken Leg", 1),
			new ItemCollectionType(typeof(RawFishSteak), "Raw Fish Steak", 1),
			new ItemCollectionType(typeof(RawLambLeg), "Raw LambLeg", 1),
			new ItemCollectionType(typeof(RawRibs), "Raw Ribs", 1),
			new ItemCollectionType(typeof(ReactiveArmorScroll), "ReactiveArmorScroll", 1),
			new ItemCollectionType(typeof(RecallScroll), "RecallScroll", 1),
			new ItemCollectionType(typeof(RedArmoire), "Red Armoire", 1),
			new ItemCollectionType(typeof(RedMisoSoup), "Red Miso Soup", 1),
			new ItemCollectionType(typeof(RefreshPotion), "Refresh Potion", 1),
			new ItemCollectionType(typeof(RefreshPotion), "Refresh Potion", 1),
			new ItemCollectionType(typeof(RepeatingCrossbow), "Repeating Crossbow", 1),
			new ItemCollectionType(typeof(ResurrectionScroll), "ResurrectionScroll", 1),
			new ItemCollectionType(typeof(RevealScroll), "RevealScroll", 1),
			new ItemCollectionType(typeof(Ribs), "Ribs", 1),
			new ItemCollectionType(typeof(RingmailArms), "Ringmail Arms", 1),
			new ItemCollectionType(typeof(RingmailChest), "Ringmail Chest", 1),
			new ItemCollectionType(typeof(RingmailGloves), "Ringmail Gloves", 1),
			new ItemCollectionType(typeof(RingmailLegs), "Ringmail Legs", 1),
			new ItemCollectionType(typeof(Robe), "Robe", 1),
			new ItemCollectionType(typeof(Ruby), "Ruby", 1),
			new ItemCollectionType(typeof(Runebook), "Runebook", 1),
			new ItemCollectionType(typeof(RunicAtlas), "Runic Atlas", 1),
			new ItemCollectionType(typeof(SackFlour), "Sack Flour", 1),
			new ItemCollectionType(typeof(Sandals), "Sandals", 1),
			new ItemCollectionType(typeof(Sapphire), "Sapphire", 1),
			new ItemCollectionType(typeof(Sausage), "Sausage", 1),
			new ItemCollectionType(typeof(SausagePizza), "Sausage Pizza", 1),
			new ItemCollectionType(typeof(Saw), "Saw", 1),
			new ItemCollectionType(typeof(Scales), "Scales", 1),
			new ItemCollectionType(typeof(Scimitar), "Scimitar", 1),
			new ItemCollectionType(typeof(SewingKit), "SewingKit", 1),
			new ItemCollectionType(typeof(SextantParts), "Sextant Parts", 1),
			new ItemCollectionType(typeof(ShadowIronIngot), "ShadowIron Ingot", 1),
			new ItemCollectionType(typeof(Shaft), "Shaft", 1),
			new ItemCollectionType(typeof(SheafOfHay), "Sheaf Of Hay", 1),
			new ItemCollectionType(typeof(ShepherdsCrook), "Shepherds Crook", 1),
			new ItemCollectionType(typeof(Shirt), "Shirt", 1),
			new ItemCollectionType(typeof(Shoes), "Shoes", 1),
			new ItemCollectionType(typeof(ShortCabinet), "Short Cabinet", 1),
			new ItemCollectionType(typeof(ShortPants), "Short Pants", 1),
			new ItemCollectionType(typeof(ShortSpear), "Short Spear", 1),
			new ItemCollectionType(typeof(Skillet), "Skillet", 1),
			new ItemCollectionType(typeof(Skirt), "Skirt", 1),
			new ItemCollectionType(typeof(SkullCap), "Skull Cap", 1),
			new ItemCollectionType(typeof(SlayerLongbow), "Slayer Longbow", 1),
			new ItemCollectionType(typeof(SledgeHammer), "Sledge Hammer", 1),
			new ItemCollectionType(typeof(SmallCrate), "Small Crate", 1),
			new ItemCollectionType(typeof(SmallFish), "Small Fish", 1),
			new ItemCollectionType(typeof(SmithyHammer), "Smithy Hammer", 1),
			new ItemCollectionType(typeof(Spear), "Spear", 1),
			new ItemCollectionType(typeof(Spellbook), "Spellbook", 1),
			new ItemCollectionType(typeof(SpidersSilk), "Spiders Silk", 1),
			new ItemCollectionType(typeof(SpoolOfThread), "Spool Of Thread", 1),
			new ItemCollectionType(typeof(Spoon), "Spoon", 1),
			new ItemCollectionType(typeof(SpoonLeft), "Spoon Left", 1),
			new ItemCollectionType(typeof(Springs), "Springs", 1),
			new ItemCollectionType(typeof(Spyglass), "Spyglass", 1),
			new ItemCollectionType(typeof(Squash), "Squash", 1),
			new ItemCollectionType(typeof(StarSapphire), "Star Sapphire", 1),
			new ItemCollectionType(typeof(Stool), "Stool", 1),
			new ItemCollectionType(typeof(StrangleScroll), "StrangleScroll", 1),
			new ItemCollectionType(typeof(StrawHat), "StrawHat", 1),
			new ItemCollectionType(typeof(StrengthPotion), "Strength Potion", 1),
			new ItemCollectionType(typeof(StrengthScroll), "StrengthScroll", 1),
			new ItemCollectionType(typeof(StuddedArms), "Studded Arms", 1),
			new ItemCollectionType(typeof(StuddedBustierArms), "Studded Bustier Arms", 1),
			new ItemCollectionType(typeof(StuddedChest), "Studded Chest", 1),
			new ItemCollectionType(typeof(StuddedGloves), "Studded Gloves", 1),
			new ItemCollectionType(typeof(StuddedGorget), "Studded Gorget", 1),
			new ItemCollectionType(typeof(StuddedLegs), "Studded Legs", 1),
			new ItemCollectionType(typeof(SulfurousAsh), "Sulfurous Ash", 1),
			new ItemCollectionType(typeof(SummonAirElementalScroll), "SummonAirElementalScroll", 1),
			new ItemCollectionType(typeof(SummonCreatureScroll), "SummonCreatureScroll", 1),
			new ItemCollectionType(typeof(SummonDaemonScroll), "SummonDaemonScroll", 1),
			new ItemCollectionType(typeof(SummonEarthElementalScroll), "SummonEarthElementalScroll", 1),
			new ItemCollectionType(typeof(SummonFamiliarScroll), "SummonFamiliarScroll", 1),
			new ItemCollectionType(typeof(SummonFireElementalScroll), "SummonFireElementalScroll", 1),
			new ItemCollectionType(typeof(SummonWaterElementalScroll), "SummonWaterElementalScroll", 1),
			new ItemCollectionType(typeof(Surcoat), "Surcoat", 1),
			new ItemCollectionType(typeof(SushiPlatter), "Sushi Platter", 1),
			new ItemCollectionType(typeof(SushiRolls), "Sushi Rolls", 1),
			new ItemCollectionType(typeof(SweetCocoaButter), "Sweet Cocoa Butter", 1),
			new ItemCollectionType(typeof(SweetDough), "Sweet Dough", 1),
			new ItemCollectionType(typeof(TallCabinet), "Tall Cabinet", 1),
			new ItemCollectionType(typeof(TallStrawHat), "Tall StrawHat", 1),
			new ItemCollectionType(typeof(TelekinisisScroll), "TelekinisisScroll", 1),
			new ItemCollectionType(typeof(TeleportScroll), "TeleportScroll", 1),
			new ItemCollectionType(typeof(Tetsubo), "Tetsubo", 1),
			new ItemCollectionType(typeof(ThighBoots), "ThighBoots", 1),
			new ItemCollectionType(typeof(ThornedWildStaff), "Thorned Wild Staff", 1),
			new ItemCollectionType(typeof(ThreeTieredCake), "Three Tiered Cake", 1),
			new ItemCollectionType(typeof(Tongs), "Tongs", 1),
			new ItemCollectionType(typeof(TotalRefreshPotion), "TotalRefresh Potion", 1),
			new ItemCollectionType(typeof(Tourmaline), "Tourmaline", 1),
			new ItemCollectionType(typeof(TribalPaint), "TribalPaint", 1),
			new ItemCollectionType(typeof(TricorneHat), "TricorneHat", 1),
			new ItemCollectionType(typeof(Tunic), "Tunic", 1),
			new ItemCollectionType(typeof(Turnip), "Turnip", 1),
			new ItemCollectionType(typeof(TwoHandedAxe), "Two Handed Axe", 1),
			new ItemCollectionType(typeof(UnbakedApplePie), "Unbaked ApplePie", 1),
			new ItemCollectionType(typeof(UnbakedFruitPie), "Unbaked FruitPie", 1),
			new ItemCollectionType(typeof(UnbakedMeatPie), "Unbaked MeatPie", 1),
			new ItemCollectionType(typeof(UnbakedPeachCobbler), "Unbaked PeachCobbler", 1),
			new ItemCollectionType(typeof(UnbakedPumpkinPie), "Unbaked PumpkinPie", 1),
			new ItemCollectionType(typeof(UnbakedQuiche), "Unbaked Quiche", 1),
			new ItemCollectionType(typeof(UncookedCheesePizza), "Uncooked CheesePizza", 1),
			new ItemCollectionType(typeof(UncookedSausagePizza), "Uncooked SausagePizza", 1),
			new ItemCollectionType(typeof(UncutCloth), "Uncut Cloth", 1),
			new ItemCollectionType(typeof(UnlockScroll), "UnlockScroll", 1),
			new ItemCollectionType(typeof(ValoriteIngot), "Valorite Ingot", 1),
			new ItemCollectionType(typeof(VampiricEmbraceScroll), "VampiricEmbraceScroll", 1),
			new ItemCollectionType(typeof(VengefulSpiritScroll), "VengefulSpiritScroll", 1),
			new ItemCollectionType(typeof(VeriteIngot), "Verite Ingot", 1),
			new ItemCollectionType(typeof(VikingSword), "Viking Sword", 1),
			new ItemCollectionType(typeof(WallOfStoneScroll), "WallOfStoneScroll", 1),
			new ItemCollectionType(typeof(WarAxe), "War Axe", 1),
			new ItemCollectionType(typeof(WarFork), "War Fork", 1),
			new ItemCollectionType(typeof(WarHammer), "War Hammer", 1),
			new ItemCollectionType(typeof(WarMace), "War Mace", 1),
			new ItemCollectionType(typeof(WasabiClumps), "Wasabi Clumps", 1),
			new ItemCollectionType(typeof(Watermelon), "Watermelon", 1),
			new ItemCollectionType(typeof(WeakenScroll), "WeakenScroll", 1),
			new ItemCollectionType(typeof(WhiteMisoSoup), "White Miso Soup", 1),
			new ItemCollectionType(typeof(WideBrimHat), "Wide Brim Hat", 1),
			new ItemCollectionType(typeof(WildStaff), "WildStaff", 1),
			new ItemCollectionType(typeof(WitherScroll), "WitherScroll", 1),
			new ItemCollectionType(typeof(WizardsHat), "Wizards Hat", 1),
			new ItemCollectionType(typeof(WoodenBench), "Wooden Bench", 1),
			new ItemCollectionType(typeof(WoodenBox), "WoodenBox", 1),
			new ItemCollectionType(typeof(WoodenChest), "Wooden Chest", 1),
			new ItemCollectionType(typeof(WoodenFootLocker), "Wooden Foot Locker", 1),
			new ItemCollectionType(typeof(WoodenKiteShield), "Wooden Kite Shield", 1),
			new ItemCollectionType(typeof(WoodenThrone), "Wooden Throne", 1),
			new ItemCollectionType(typeof(Wool), "Wool", 1),
			new ItemCollectionType(typeof(WraithFormScroll), "WraithFormScroll", 1),
			new ItemCollectionType(typeof(YellowGourd), "Yellow Gourd", 1),
			new ItemCollectionType(typeof(YewLog), "YewLog", 1),
			new ItemCollectionType(typeof(Yumi), "Yumi", 1),
        };

        public static int Random()
        {
            return Utility.Random(Items.Length);
        }

        private Type m_Type;
        public Type Type
        {
            get { return m_Type; }
            set { m_Type = value; }
        }

        private string m_Name;
        public string Name
        {
            get { return m_Name; }
            set { m_Name = value; }
        }

        private int m_Rarity;
        public int Rarity
        {
            get { return m_Rarity; }
            set { m_Rarity = value; }
        }

        public ItemCollectionType(Type type, string name, int rarity)
        {
            m_Type = type;
            m_Name = name;
            m_Rarity = rarity;
        }
    }
}
